controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login_check:
    path: /api/login_check

view_token:
    path: /api/token
    controller: App\Controller\TokenController::viewToken
    methods: GET
